# Generated by Django 5.0 on 2023-12-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morse', '0002_morseaudiopath'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='audio_file_user')),
            ],
        ),
    ]
